[package]
name = "splitsql-benchmarks"
description = "SplitSQL Benchmarks"
edition = { workspace = true }


[dependencies]
liquid-cache-server = { workspace = true }
liquid-cache-client = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
datafusion = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
arrow-flight = { workspace = true }
tonic = { workspace = true }
clap = "4.5.27"
env_logger = "0.11.5"
url = { workspace = true }
mimalloc = "0.1.43"
