[package]
name = "datafusion-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "53.3.0"
arrow-flight = { version = "53.3.0", features = ["flight-sql-experimental"] }
arrow-schema = { version = "53.3.0", features = ["serde"] }
parquet = "53.3.0"
# Point to official repo until: https://github.com/apache/datafusion/pull/14139
datafusion = { git = "https://github.com/XiangpengHao/datafusion.git", branch = "config-fix" }
async-trait = "0.1.83"
futures = "0.3.31"
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tonic = { version = "0.12", features = [
	"tls-native-roots",
	"tls-webpki-roots",
] }
dashmap = "6.1.0"
tokio = "1.42.0"
uuid = "1.7.0"
prost = "0.13.3"
prost-derive = "0.13.3"
object_store = "0.11.2"
url = "2.5.4"
itertools = "0.14.0"

[dev-dependencies]
env_logger = "0.11.5"
rand = "0.8.5"


[[example]]
name = "server"
path = "examples/server.rs"

[[example]]
name = "client"
path = "examples/client.rs"
