[toolchain]
# I really don't want to use nightly, but we have to, until:
# https://github.com/spiraldb/fastlanes/issues/45 is fixed.
channel = "nightly"
components = ["rustfmt", "clippy", "rust-src"]
