name: "Rust Setup"
description: "Sets up Rust with sccache and caching"

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        components: rustfmt, clippy, rust-src
        toolchain: nightly-2025-01-24

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.7

    - name: Cache sccache output
      uses: actions/cache@v4
      with:
        # these represent dependencies downloaded by cargo
        # and thus do not depend on the OS, arch nor rust version.
        #
        # source https://github.com/actions/cache/blob/main/examples.md#rust---cargo
        path: |
          /usr/local/cargo/bin/
          /usr/local/cargo/registry/index/
          /usr/local/cargo/registry/cache/
          /usr/local/cargo/git/db/
        key: ${{ runner.os }}-cache4-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cache4-

    - name: Show initial sccache stats
      shell: bash
      run: sccache --show-stats

    - name: Configure runtime env
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV  
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV 
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        echo "RUSTFLAGS=-C debuginfo=line-tables-only -C incremental=false" >> $GITHUB_ENV
