name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Basic check
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check documentation
        run: cargo doc --no-deps --document-private-items --all-features
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Show final sccache stats
        run: sccache --show-stats

  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      
      - name: Run tests
        run: cargo test --verbose

      - name: Show sccache stats
        run: sccache --show-stats

  address_san:
    name: Address Sanitizer
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      
      - name: Run address sanitizer
        run: >
          env RUSTFLAGS="-Z sanitizer=address" cargo test -Zbuild-std --target x86_64-unknown-linux-gnu --tests

      - name: Show sccache stats
        run: sccache --show-stats

  memory_san:
    name: Memory Sanitizer
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      
      - name: Run memory sanitizer
        run: >
          env RUSTFLAGS="-Z sanitizer=memory" cargo test -Zbuild-std --target x86_64-unknown-linux-gnu --tests

      - name: Show sccache stats
        run: sccache --show-stats

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      
      - name: Build LiquidCache server
        run: cargo build --release --bin bench_server

      - name: Start LiquidCache server
        run: env RUST_LOG=info nohup cargo run --release --bin bench_server &> server.log &

      - name: Run simple ClickBench
        run: |
          env RUST_LOG=info cargo run --release --bin bench_client -- --query-path benchmark/queries.sql --file examples/small_hits.parquet

      - name: Kill LiquidCache server
        run: pkill bench_server || true

      - name: Download ClickBench partition 0
        run: |
          wget https://datasets.clickhouse.com/hits_compatible/athena_partitioned/hits_0.parquet -O benchmark/data/hits_0.parquet

      - name: Start LiquidCache server (for partition 0)
        run: env RUST_LOG=info nohup cargo run --release --bin bench_server &> server.log &

      - name: Run ClickBench partition 0
        run: |
          env RUST_LOG=info cargo run --release --bin bench_client -- --query-path benchmark/queries.sql --file benchmark/data/hits_0.parquet

      - name: Display server logs (on failure)
        if: failure()
        run: cat server.log

      - name: Show final sccache stats
        run: sccache --show-stats
